Traceback (most recent call last):
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Data processing
import numpy as np
import pandas as pd

# Wizualizacja
from matplotlib import pyplot as plt
import seaborn as sns

# ML
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor, plot_tree, export_text
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
import lightgbm
import xgboost
------------------

----- stderr -----

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\knajmajer\AppData\Local\Temp\ipykernel_23084\1541751538.py", line 3, in <module>
    import pandas as pd
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\pandas\__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\pandas\core\api.py", line 1, in <module>
    from pandas._libs import (
  File "C:\Users\knajmajer\.conda\envs\pg_env\Lib\site-packages\pandas\_libs\__init__.py", line 17, in <module>
    import pandas._libs.pandas_datetime  # noqa: F401 # isort: skip # type: ignore[reportUnusedImport]
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mImportError[0m                               Traceback (most recent call last)
Cell [1;32mIn[1], line 3[0m
[0;32m      1[0m [38;5;66;03m# Data processing[39;00m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m----> 3[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m      5[0m [38;5;66;03m# Wizualizacja[39;00m
[0;32m      6[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m pyplot [38;5;28;01mas[39;00m plt

File [1;32m~\.conda\envs\pg_env\Lib\site-packages\pandas\__init__.py:49[0m
[0;32m     46[0m [38;5;66;03m# let init-time option registration happen[39;00m
[0;32m     47[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcore[39;00m[38;5;21;01m.[39;00m[38;5;21;01mconfig_init[39;00m  [38;5;66;03m# pyright: ignore[reportUnusedImport] # noqa: F401[39;00m
[1;32m---> 49[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcore[39;00m[38;5;21;01m.[39;00m[38;5;21;01mapi[39;00m [38;5;28;01mimport[39;00m (
[0;32m     50[0m     [38;5;66;03m# dtype[39;00m
[0;32m     51[0m     ArrowDtype,
[0;32m     52[0m     Int8Dtype,
[0;32m     53[0m     Int16Dtype,
[0;32m     54[0m     Int32Dtype,
[0;32m     55[0m     Int64Dtype,
[0;32m     56[0m     UInt8Dtype,
[0;32m     57[0m     UInt16Dtype,
[0;32m     58[0m     UInt32Dtype,
[0;32m     59[0m     UInt64Dtype,
[0;32m     60[0m     Float32Dtype,
[0;32m     61[0m     Float64Dtype,
[0;32m     62[0m     CategoricalDtype,
[0;32m     63[0m     PeriodDtype,
[0;32m     64[0m     IntervalDtype,
[0;32m     65[0m     DatetimeTZDtype,
[0;32m     66[0m     StringDtype,
[0;32m     67[0m     BooleanDtype,
[0;32m     68[0m     [38;5;66;03m# missing[39;00m
[0;32m     69[0m     NA,
[0;32m     70[0m     isna,
[0;32m     71[0m     isnull,
[0;32m     72[0m     notna,
[0;32m     73[0m     notnull,
[0;32m     74[0m     [38;5;66;03m# indexes[39;00m
[0;32m     75[0m     Index,
[0;32m     76[0m     CategoricalIndex,
[0;32m     77[0m     RangeIndex,
[0;32m     78[0m     MultiIndex,
[0;32m     79[0m     IntervalIndex,
[0;32m     80[0m     TimedeltaIndex,
[0;32m     81[0m     DatetimeIndex,
[0;32m     82[0m     PeriodIndex,
[0;32m     83[0m     IndexSlice,
[0;32m     84[0m     [38;5;66;03m# tseries[39;00m
[0;32m     85[0m     NaT,
[0;32m     86[0m     Period,
[0;32m     87[0m     period_range,
[0;32m     88[0m     Timedelta,
[0;32m     89[0m     timedelta_range,
[0;32m     90[0m     Timestamp,
[0;32m     91[0m     date_range,
[0;32m     92[0m     bdate_range,
[0;32m     93[0m     Interval,
[0;32m     94[0m     interval_range,
[0;32m     95[0m     DateOffset,
[0;32m     96[0m     [38;5;66;03m# conversion[39;00m
[0;32m     97[0m     to_numeric,
[0;32m     98[0m     to_datetime,
[0;32m     99[0m     to_timedelta,
[0;32m    100[0m     [38;5;66;03m# misc[39;00m
[0;32m    101[0m     Flags,
[0;32m    102[0m     Grouper,
[0;32m    103[0m     factorize,
[0;32m    104[0m     unique,
[0;32m    105[0m     value_counts,
[0;32m    106[0m     NamedAgg,
[0;32m    107[0m     array,
[0;32m    108[0m     Categorical,
[0;32m    109[0m     set_eng_float_format,
[0;32m    110[0m     Series,
[0;32m    111[0m     DataFrame,
[0;32m    112[0m )
[0;32m    114[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcore[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdtypes[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdtypes[39;00m [38;5;28;01mimport[39;00m SparseDtype
[0;32m    116[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtseries[39;00m[38;5;21;01m.[39;00m[38;5;21;01mapi[39;00m [38;5;28;01mimport[39;00m infer_freq

File [1;32m~\.conda\envs\pg_env\Lib\site-packages\pandas\core\api.py:1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01m_libs[39;00m [38;5;28;01mimport[39;00m (
[0;32m      2[0m     NaT,
[0;32m      3[0m     Period,
[0;32m      4[0m     Timedelta,
[0;32m      5[0m     Timestamp,
[0;32m      6[0m )
[0;32m      7[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01m_libs[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmissing[39;00m [38;5;28;01mimport[39;00m NA
[0;32m      9[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcore[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdtypes[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdtypes[39;00m [38;5;28;01mimport[39;00m (
[0;32m     10[0m     ArrowDtype,
[0;32m     11[0m     CategoricalDtype,
[1;32m   (...)[0m
[0;32m     14[0m     PeriodDtype,
[0;32m     15[0m )

File [1;32m~\.conda\envs\pg_env\Lib\site-packages\pandas\_libs\__init__.py:17[0m
[0;32m     13[0m [38;5;66;03m# Below imports needs to happen first to ensure pandas top level[39;00m
[0;32m     14[0m [38;5;66;03m# module gets monkeypatched with the pandas_datetime_CAPI[39;00m
[0;32m     15[0m [38;5;66;03m# see pandas_datetime_exec in pd_datetime.c[39;00m
[0;32m     16[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01m_libs[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpandas_parser[39;00m  [38;5;66;03m# isort: skip # type: ignore[reportUnusedImport][39;00m
[1;32m---> 17[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01m_libs[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpandas_datetime[39;00m  [38;5;66;03m# noqa: F401 # isort: skip # type: ignore[reportUnusedImport][39;00m
[0;32m     18[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01m_libs[39;00m[38;5;21;01m.[39;00m[38;5;21;01minterval[39;00m [38;5;28;01mimport[39;00m Interval
[0;32m     19[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01m_libs[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtslibs[39;00m [38;5;28;01mimport[39;00m (
[0;32m     20[0m     NaT,
[0;32m     21[0m     NaTType,
[1;32m   (...)[0m
[0;32m     26[0m     iNaT,
[0;32m     27[0m )

[1;31mImportError[0m: numpy.core.multiarray failed to import

